name: Build libaec native binaries
on: workflow_dispatch

jobs:
  windows_build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          pacboy: >-
            toolchain:p
            cmake:p
            ninja:p
      - name: Build
        shell: msys2 {0}
        working-directory: lib/libaec 
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../artifacts ..
          ninja install
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: win-lib
          path: lib/libaec/artifacts/bin/libaec.dll
          if-no-files-found: error
  unix_build:
    runs-on: ${{ matrix.configs.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations
      fail-fast: false

      matrix:
        configs: [
          { os: ubuntu-latest, name: linux-lib, target: libaec.so.* },
          { os: macos-latest, name: mac-lib, target: libaec*.dylib }
        ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        working-directory: lib/libaec 
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../artifacts ..
          make install
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.configs.name }}
          path: lib/libaec/artifacts/lib/${{ matrix.configs.target }}
          if-no-files-found: error