name: Build libaec native binaries
on: workflow_dispatch

jobs:
  windows_build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          pacboy: >-
            toolchain:p
            cmake:p
            ninja:p
      - name: Build
        shell: msys2 {0}
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../artifacts ..
          make install